###
GET https://bbfquestions.vercel.app/api/questions
Content-Type: application/json

###
POST https://bbfquestions.vercel.app/api/users
Content-Type: application/json

{
    "username": "admin"
}


###
POST https://bbfquestions.vercel.app/api/validate/admin
Content-Type: application/json
